import { describe, expect, it } from 'vitest';
import { simulate } from '../src/core/calculator.js';
import type { SimulateInput, SimulateResult } from '../src/types/domain.js';
import fixture from './fixtures/golden-simulations.json' with { type: 'json' };

/**
 * Golden quarterly-compounding regression scenarios.
 *
 * The fixture was generated by `simulate()` itself and locked in -- so this
 * suite is a behavioural regression net rather than an external-parity
 * check. Cross-validation against IGCP's own web simulator lives in
 * `compare/igcp-simulator.ts`; the goal here is to surface any drift in
 * calendar logic, base-rate composition, premium-tier resolution or
 * banker-rounding before it reaches the comparison harness.
 *
 * Each scenario is asserted **structurally** -- the loaded fixture's
 * `expected` block is compared field-by-field against the live `simulate()`
 * output, so any change to a single number or schedule row will fail with a
 * pinpoint diff.
 */

interface GoldenScenario {
  readonly id: string;
  readonly description: string;
  readonly input: SimulateInput;
  readonly expected: Omit<SimulateResult, 'seriesMetadata'>;
}

const scenarios = (fixture as { readonly scenarios: readonly GoldenScenario[] }).scenarios;

function stripMetadata(result: SimulateResult): Omit<SimulateResult, 'seriesMetadata'> {
  const { seriesMetadata: _seriesMetadata, ...rest } = result;
  return rest;
}

describe('simulate — golden quarterly-compounding scenarios', () => {
  it('fixture is non-empty and has unique ids', () => {
    expect(scenarios.length).toBeGreaterThan(0);
    const ids = scenarios.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  for (const scenario of scenarios) {
    it(`${scenario.id} — ${scenario.description}`, () => {
      const result = simulate(scenario.input);
      expect(stripMetadata(result)).toEqual(scenario.expected);
      // Sanity: seriesMetadata is always present even when stripped above.
      expect(result.seriesMetadata.code).toBe('F');
    });
  }
});

describe('simulate — invariants beyond the locked fixtures', () => {
  // These assertions hold for every scenario in the fixture and act as a
  // light double-check on the locked numbers themselves.
  it('currentValueNet === units + totalInterestNet for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const expected = (Number(scenario.input.units) + Number(result.totalInterestNet)).toFixed(2);
      expect(result.currentValueNet).toBe(expected);
    }
  });

  it('currentValueGross === units + totalInterestGross for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const expected = (Number(scenario.input.units) + Number(result.totalInterestGross)).toFixed(
        2,
      );
      expect(result.currentValueGross).toBe(expected);
    }
  });

  // Tolerance: the headline totals (`totalInterestGross`, `totalIrsWithheld`,
  // `totalInterestNet`) are each rounded *independently* from the same
  // never-quantized running balance, so the per-cent identity
  // `net = gross − IRS` can drift by up to one cent. We accept ≤ 0.01 EUR.
  it('totalInterestNet ≈ totalInterestGross - totalIrsWithheld (±0.01 EUR) for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const diff =
        Number(result.totalInterestNet) -
        (Number(result.totalInterestGross) - Number(result.totalIrsWithheld));
      expect(Math.abs(diff)).toBeLessThanOrEqual(0.01);
    }
  });

  // Tolerance: each schedule row is an independently-rounded display snapshot
  // of the high-precision running balance, so summing the rounded rows can
  // diverge from the rounded headline totals by up to one cent (and across
  // many quarters, the accumulated rounding can stretch a couple of cents).
  // We accept ≤ 0.01 EUR per identity here.
  it('schedule rows reconcile to totalInterestGross / Net / Withheld within ±0.01 EUR', () => {
    for (const scenario of scenarios.filter((s) => s.input.includeSchedule)) {
      const result = simulate(scenario.input);
      const sched = result.schedule;
      expect(sched).toBeDefined();
      if (!sched) continue;
      const sumGross = sched.reduce((sum, row) => sum + Number(row.interestGross), 0);
      const sumNet = sched.reduce((sum, row) => sum + Number(row.interestNet), 0);
      const sumIrs = sched.reduce((sum, row) => sum + Number(row.irsWithheld), 0);
      expect(Math.abs(sumGross - Number(result.totalInterestGross))).toBeLessThanOrEqual(0.01);
      expect(Math.abs(sumNet - Number(result.totalInterestNet))).toBeLessThanOrEqual(0.01);
      expect(Math.abs(sumIrs - Number(result.totalIrsWithheld))).toBeLessThanOrEqual(0.01);
    }
  });
});

describe('simulate — input validation', () => {
  it('rejects subscriptionDate before Série F open date (2023-06-01)', () => {
    expect(() => simulate({ series: 'F', subscriptionDate: '2023-05-31', units: 1000 })).toThrow();
  });

  it('rejects asOfDate before subscriptionDate', () => {
    expect(() =>
      simulate({
        series: 'F',
        subscriptionDate: '2024-03-15',
        units: 1000,
        asOfDate: '2024-03-14',
      }),
    ).toThrow();
  });

  it('rejects units below the series minimum', () => {
    expect(() => simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 99 })).toThrow();
  });

  it('rejects units above the series maximum', () => {
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 100_001 }),
    ).toThrow();
  });

  it('rejects irsRate outside [0, 1]', () => {
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 1000, irsRate: -0.01 }),
    ).toThrow();
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 1000, irsRate: 1.01 }),
    ).toThrow();
  });

  it('rejects Série E subscriptionDate after the 2023-06-01 closure', () => {
    expect(() => simulate({ series: 'E', subscriptionDate: '2023-06-02', units: 1000 })).toThrow();
  });

  it('accepts Série E units up to the 250.000€ ceiling', () => {
    expect(() =>
      simulate({
        series: 'E',
        subscriptionDate: '2018-01-15',
        units: 250_000,
        asOfDate: '2018-04-15',
      }),
    ).not.toThrow();
    expect(() =>
      simulate({ series: 'E', subscriptionDate: '2018-01-15', units: 250_001 }),
    ).toThrow();
  });
});

/**
 * Série E smoke test — exercises the cross-cutting plumbing on a single
 * cohort that spans the year-5 → year-6 premium boundary and (since
 * maturity is 10 years rather than Série F's 15) sits within reach of the
 * `matured` flag.
 *
 * Cohort: subscribed 2018-01-15 (Série E was open from 2017-11-01 through
 * 2023-06-01), evaluated at 2026-04-19. Subscription day-of-month is 15,
 * which dodges every quarterly month-end roll-forward edge case. Specific
 * monetary totals are not locked here because they depend on the bundled
 * Euribor 3M dataset (which evolves with each refresh); instead the test
 * pins the structural invariants:
 *
 *   - 33 completed quarters between 2018-01-15 and 2026-04-15.
 *   - The premium tier flips from +0.50% to +1.00% on the 1st quarter that
 *     starts on or after the 5th anniversary (2023-01-15 — quarter 20,
 *     0-indexed 20 in `schedule`).
 *   - Maturity falls on 2028-01-15 and `matured` is `false` at 2026-04-19.
 *   - The capitalization identities (`net = gross − IRS`,
 *     `currentValueNet = units + totalInterestNet`) hold at the totals
 *     level, mirroring the Série F invariants block above.
 */
describe('simulate — Série E smoke test', () => {
  const input: SimulateInput = {
    series: 'E',
    subscriptionDate: '2018-01-15',
    units: 1000,
    asOfDate: '2026-04-19',
    includeSchedule: true,
  };

  it('produces 33 quarterly capitalizations and reports the 10-year maturity date', () => {
    const result = simulate(input);
    expect(result.series).toBe('E');
    expect(result.seriesMetadata.code).toBe('E');
    expect(result.maturityDate).toBe('2028-01-15');
    expect(result.matured).toBe(false);
    expect(result.schedule).toBeDefined();
    expect(result.schedule?.length).toBe(33);
  });

  it('crosses the year-5 → year-6 premium boundary at quarter 20 (2023-01-15)', () => {
    const result = simulate(input);
    const schedule = result.schedule;
    expect(schedule).toBeDefined();
    if (!schedule) return;
    // First quarter sits in contract year 1 → no premium.
    expect(schedule[0]?.premiumTier).toEqual({ fromYear: 1, toYear: 1, ratePct: '0.00' });
    // Quarter 19 (0-indexed) ends 2023-01-15 — the 5th anniversary.
    // The quarter *starting* on 2023-01-15 is the first one in contract
    // year 6, so its premium jumps from +0.50% to +1.00%.
    expect(schedule[19]?.quarterEndDate).toBe('2023-01-15');
    expect(schedule[19]?.premiumTier).toEqual({ fromYear: 2, toYear: 5, ratePct: '0.50' });
    expect(schedule[20]?.premiumTier).toEqual({ fromYear: 6, toYear: 10, ratePct: '1.00' });
  });

  it('preserves the cents-level capitalization identities at the totals level', () => {
    const result = simulate(input);
    const principal = input.units;
    // Same tolerance as the cross-cutting invariants block above:
    // gross/IRS/net are rounded independently from a high-precision balance,
    // so the `net = gross − IRS` identity can drift up to one cent. The
    // currentValue* identities ride on the same rounding pipeline as their
    // total* counterparts, so they should reconcile exactly.
    const netDiff =
      Number(result.totalInterestNet) -
      (Number(result.totalInterestGross) - Number(result.totalIrsWithheld));
    expect(Math.abs(netDiff)).toBeLessThanOrEqual(0.01);
    expect(result.currentValueNet).toBe((principal + Number(result.totalInterestNet)).toFixed(2));
    expect(result.currentValueGross).toBe(
      (principal + Number(result.totalInterestGross)).toFixed(2),
    );
  });

  it('reports matured=true once asOfDate reaches the 10-year maturity date', () => {
    const result = simulate({
      series: 'E',
      subscriptionDate: '2018-01-15',
      units: 1000,
      asOfDate: '2028-01-15',
    });
    expect(result.matured).toBe(true);
    expect(result.maturityDate).toBe('2028-01-15');
  });
});

describe('simulate — Série E per-unit quote parity', () => {
  it('reproduces the published quote for a 2023-03-29 cohort at the 2026-03-29 capitalization', () => {
    const result = simulate({
      series: 'E',
      subscriptionDate: '2023-03-29',
      units: 1000,
      asOfDate: '2026-04-19',
      includeSchedule: true,
    });

    expect(result.currentUnitQuote).toBe('1.08340');
    expect(result.currentValueNet).toBe('1083.40');
    expect(result.schedule).toHaveLength(12);
    expect(result.schedule?.at(-1)?.unitQuoteAfter).toBe('1.08340');
  });
});
