import { describe, expect, it } from 'vitest';
import { simulate } from '../src/core/calculator.js';
import type { SimulateInput, SimulateResult } from '../src/types/domain.js';
import fixture from './fixtures/golden-simulations.json' with { type: 'json' };

/**
 * Golden quarterly-compounding regression scenarios.
 *
 * The fixture was generated by `simulate()` itself and locked in -- so this
 * suite is a behavioural regression net rather than an external-parity
 * check. Cross-validation against IGCP's own web simulator lives in
 * `compare/igcp-simulator.ts`; the goal here is to surface any drift in
 * calendar logic, base-rate composition, premium-tier resolution or
 * banker-rounding before it reaches the comparison harness.
 *
 * Each scenario is asserted **structurally** -- the loaded fixture's
 * `expected` block is compared field-by-field against the live `simulate()`
 * output, so any change to a single number or schedule row will fail with a
 * pinpoint diff.
 */

interface GoldenScenario {
  readonly id: string;
  readonly description: string;
  readonly input: SimulateInput;
  readonly expected: Omit<SimulateResult, 'seriesMetadata'>;
}

const scenarios = (fixture as { readonly scenarios: readonly GoldenScenario[] }).scenarios;

function stripMetadata(result: SimulateResult): Omit<SimulateResult, 'seriesMetadata'> {
  const { seriesMetadata: _seriesMetadata, ...rest } = result;
  return rest;
}

describe('simulate — golden quarterly-compounding scenarios', () => {
  it('fixture is non-empty and has unique ids', () => {
    expect(scenarios.length).toBeGreaterThan(0);
    const ids = scenarios.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  for (const scenario of scenarios) {
    it(`${scenario.id} — ${scenario.description}`, () => {
      const result = simulate(scenario.input);
      expect(stripMetadata(result)).toEqual(scenario.expected);
      // Sanity: seriesMetadata is always present even when stripped above.
      expect(result.seriesMetadata.code).toBe('F');
    });
  }
});

describe('simulate — invariants beyond the locked fixtures', () => {
  // These assertions hold for every scenario in the fixture and act as a
  // light double-check on the locked numbers themselves.
  it('currentValueNet === units + totalInterestNet for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const expected = (Number(scenario.input.units) + Number(result.totalInterestNet)).toFixed(2);
      expect(result.currentValueNet).toBe(expected);
    }
  });

  it('currentValueGross === units + totalInterestGross for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const expected = (Number(scenario.input.units) + Number(result.totalInterestGross)).toFixed(
        2,
      );
      expect(result.currentValueGross).toBe(expected);
    }
  });

  it('totalInterestNet === totalInterestGross - totalIrsWithheld for every scenario', () => {
    for (const scenario of scenarios) {
      const result = simulate(scenario.input);
      const expected = (
        Number(result.totalInterestGross) - Number(result.totalIrsWithheld)
      ).toFixed(2);
      expect(result.totalInterestNet).toBe(expected);
    }
  });

  it('schedule rows reconcile to totalInterestGross / Net / Withheld', () => {
    for (const scenario of scenarios.filter((s) => s.input.includeSchedule)) {
      const result = simulate(scenario.input);
      const sched = result.schedule;
      expect(sched).toBeDefined();
      if (!sched) continue;
      const sumGross = sched.reduce((sum, row) => sum + Number(row.interestGross), 0).toFixed(2);
      const sumNet = sched.reduce((sum, row) => sum + Number(row.interestNet), 0).toFixed(2);
      const sumIrs = sched.reduce((sum, row) => sum + Number(row.irsWithheld), 0).toFixed(2);
      expect(sumGross).toBe(result.totalInterestGross);
      expect(sumNet).toBe(result.totalInterestNet);
      expect(sumIrs).toBe(result.totalIrsWithheld);
    }
  });
});

describe('simulate — input validation', () => {
  it('rejects subscriptionDate before Série F open date (2023-06-01)', () => {
    expect(() => simulate({ series: 'F', subscriptionDate: '2023-05-31', units: 1000 })).toThrow();
  });

  it('rejects asOfDate before subscriptionDate', () => {
    expect(() =>
      simulate({
        series: 'F',
        subscriptionDate: '2024-03-15',
        units: 1000,
        asOfDate: '2024-03-14',
      }),
    ).toThrow();
  });

  it('rejects units below the series minimum', () => {
    expect(() => simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 99 })).toThrow();
  });

  it('rejects units above the series maximum', () => {
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 100_001 }),
    ).toThrow();
  });

  it('rejects irsRate outside [0, 1]', () => {
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 1000, irsRate: -0.01 }),
    ).toThrow();
    expect(() =>
      simulate({ series: 'F', subscriptionDate: '2024-03-15', units: 1000, irsRate: 1.01 }),
    ).toThrow();
  });
});
